### ISSUE TITLE
執行pred.fun時發生錯誤．．．．

### ISSUE THREAD

**Issue by zardabab** [f496328mm/kaggle_Rossmann_Store_Sales#1]
![image](https://cloud.githubusercontent.com/assets/25669320/24195645/82b4cbe8-0f35-11e7-88ac-e045a27f0d5c.png)

您好，我試著run您的程式，但在執行result3 = pred.fun(main.train.x,main.train.y,main.test3)
卻發生如圖的錯誤，能否請您指導一下呢?感謝~

**Comment by linsamtw** [comment]
已更新function
